name: HtmlBlock
version: 0.1.0
description: A sample web application
dependencies:
  gamelib:
    git: git://github.com/gjersvik/gamelib.git
  box2d: any
  browser: any
dev_dependencies:
  unittest: any
