name: rougeplanet
author: Ole Martin Gjersvik
description: A sample web application
dependencies:
  gamelib:
    path: ../gamelib
  box2d:
    git: git://github.com/darty-grits/dartbox2d.git
  browser: any
dev_dependencies:
  unittest: any
  